### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by Larkin-man** [Larkin-man/Character-sheet#1]
- [ ] клик по механике выводит сообщение
- [x] в таблицы вместо Он - Враг
- [x] 	не выводит исходное значение выносливость мастер
- [ ] ширина минимальная больше
- [x] 	опции формы нового предмета расширить
- [x] 	там максимум 100 это мало
- [x] 	лишние строки в таблице если очень много и перерасчет, лучше го в первую всегда
- [ ] 	убрать таблицу если механики нет?
- [ ] таблица боя подробней
- [x] 	стереть все предметы - не изменяется вес
- [ ] сообщения о макросах другим шрифтом
- [ ] прокрутить вверх после применения текста
- [ ] увеличьте шрифт инвентаря
- [ ] вероятности
- [x] 	начать заново: инвентарь го01 восстановить
- [ ] иконку макроса поменять и окончена запись
- [ ] перед обновлением текста параграфа мельтешит, лучше begin update
- [ ] снизу и справа рамка другая
